import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  // For static hosting, ensure SPA fallback is generated by your host.
  // Vercel fallback configured in vercel.json
  server: {
    port: 5173,
    proxy: {
      '/api': {
        target: 'https://nammakoda1234.onrender.com',
        changeOrigin: true,
        ws: true,
        secure: true
      }
    }
  }
})


